spring.application.name=companyhouse
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/companyhouse
spring.datasource.username=postgres
spring.datasource.password=postgres
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
springdoc.swagger-ui.enabled=true
app.security.username=admin
app.security.password=admin123